export {
  createDatabaseClient,
  getPrismaClient,
  resetPrismaClientForTests,
} from "./client.js";
export type { DatabaseClient } from "./client.js";
export {
  TestDatabaseError,
  applyTestDatabaseUrlFromEnv,
  assertAllowedTestDatabaseIdentity,
  assertDestructiveTestDatabaseAllowed,
  cleanupLifecycleTablesForTests,
  parseDatabaseIdentity,
} from "./test-database.js";
export type { DatabaseIdentity } from "./test-database.js";
export { ResearchRepository } from "./research-repository.js";
export type { SaveCollectionSummary, ResearchItemForAnalysis } from "./research-repository.js";
export {
  JobRepository,
  JobStateError,
  LockError,
  buildLockKey,
  DEFAULT_LOCK_TTL_MS,
} from "./job-repository.js";
export type {
  CreateJobInput,
  ProgressUpdate,
  RecordJobErrorInput,
} from "./job-repository.js";
export {
  ScheduleRepository,
  DEFAULT_SCHEDULE_LOCK_TTL_MS,
  DEFAULT_SCHEDULE_GRACE_MS,
  DEFAULT_SCHEDULER_BATCH_SIZE,
} from "./schedule-repository.js";
export type {
  ScheduleParameters,
  CreateScheduleInput,
  UpdateScheduleInput,
  RecordScheduleRunInput,
  CompleteScheduleRunInput,
} from "./schedule-repository.js";
export {
  NotificationRepository,
  buildNotificationDeduplicationKey,
  DEFAULT_NOTIFICATION_BATCH_SIZE,
  DEFAULT_SENDING_STALE_MS,
} from "./notification-repository.js";
export type { CreateNotificationInput } from "./notification-repository.js";
export { AnalysisRepository } from "./analysis-repository.js";
export type {
  CreateAnalysisRunInput,
  SaveProductAnalysisInput,
  CreateContentCandidateInput,
} from "./analysis-repository.js";
export { ContentRepository, ContentStateError } from "./content-repository.js";
export type {
  CreateGenerationRunInput,
  CreateGeneratedContentInput,
  ValidationIssueInput,
} from "./content-repository.js";
export {
  XPublicationRepository,
  XPublicationStateError,
} from "./x-publication-repository.js";
export type {
  CreatePublicationInput,
  CreatePublicationPostInput,
  PublicationWithPosts,
} from "./x-publication-repository.js";
export {
  XOptimizationRepository,
  XOptimizationStateError,
} from "./x-optimization-repository.js";
export {
  XOpsRepository,
  XOpsStateError,
  hashProductKey,
  hashNormalizedBody,
  normalizePostBody,
} from "./x-ops-repository.js";
export { XLiveRepository } from "./x-live-repository.js";
export { LifecycleRepository } from "./lifecycle-repository.js";
export type {
  UpsertAffiliateProviderInput,
  UpsertAffiliateProductInput,
  CreateSourceDocumentInput,
  CreateResearchFindingInput,
  CreateTopicCandidateInput,
  CreateStrategyInput,
  CreateContentInput,
  CreateContentVersionInput,
  CreateClaimInput,
  AddClaimSourceInput,
  AttachVersionClaimInput,
  CreatePolicyRuleInput,
  CreatePolicyEvaluationInput,
  CreateReviewInput,
  CreateRevisionActionInput,
  CreatePublicationTargetInput,
  UpdatePublicationTargetInput,
  CreatePublicationRecordInput,
  UpsertProductLinkInput,
  CreateProductLinkUsageInput,
  CreateLinkReplacementEventInput,
  UpdateProductLinkReplacementInput,
  CreateAnalyticsSnapshotInput,
  CreateModelRunInput,
  CompleteModelRunInput,
  CreateCostRecordInput,
  CreateOperatorJobInput,
} from "./lifecycle-repository.js";
export { P5Repository } from "./p5-repository.js";
export type {
  CreateAnalyticsAggregateInput,
  CreateEvaluationInput,
  CreateExperimentInput,
  CreateExperimentResultInput,
  CreateLearningRuleInput,
  CreateStrategyFeedbackInput,
} from "./p5-repository.js";
export { P6Repository } from "./p6-repository.js";
export { AdminRepository } from "./admin-repository.js";
export { ArticlePatternRepository } from "./article-pattern-repository.js";
export type {
  CreateArticleStructureObservationInput,
  CreateArticleFormatDefinitionInput,
  UpdateArticleFormatDefinitionInput,
} from "./article-pattern-repository.js";
export { EditorialBrainRepository } from "./editorial-brain-repository.js";
export type {
  CreateEditorialBrainRunInput,
  CompleteEditorialBrainRunInput,
  CreateEditorialExperienceInput,
  RetrieveEditorialExperienceQuery,
} from "./editorial-brain-repository.js";
export {
  PrismaClient,
  SourceType,
  Prisma,
  ResearchJobStatus,
  ResearchJobType,
  ResearchScheduleType,
  ResearchScheduleTriggerType,
  ResearchScheduleRunStatus,
  ResearchNotificationEventType,
  ResearchNotificationChannelType,
  ResearchNotificationStatus,
  AnalysisType,
  AnalysisRunStatus,
  EligibilityStatus,
  ContentCandidateType,
  ContentTargetChannel,
  ContentCandidateStatus,
  ImageUsageStatus,
  ContentGenerationRunStatus,
  GeneratedContentType,
  GeneratedContentStatus,
  ContentValidationIssueType,
  ContentValidationSeverity,
  ContentReviewDecision,
  XPublicationStrategyType,
  XPublicationStatus,
  XPublicationPostRole,
  XPublicationPostStatus,
  XExperimentStatus,
  XExperimentAllocationMethod,
  XStrategyConfidenceLevel,
  XOptimizationRunStatus,
  XOptimizationDimension,
  XOptimizationFindingType,
  XOptimizationRecommendationStatus,
  XOptimizationPriority,
  XOptimizationApplicationStatus,
  XProductReservationStatus,
  XAuditActorType,
  XAuditResult,
  XApiCredentialStatus,
  XOAuthSessionStatus,
  XApiUsageSource,
  XApiBudgetPeriodType,
  XApiBudgetStatus,
  ContentLifecycleStatus,
  ContentVersionStatus,
  ContentFormatCategory,
  StrategyStatus,
  ClaimType,
  ClaimStatus,
  PolicySeverity,
  PolicyEvalResult,
  ReviewResult,
  PublicationApprovalMode,
  PublicationTargetStatus,
  PublicationPlatform,
  ProductLinkType,
  AffiliateReplacementStatus,
  ProductLinkUsageKind,
  LinkReplacementEventStatus,
  MonetizationStatus,
  BudgetScopeType,
  ModelRunStatus,
} from "@prisma/client";
export type {
  ResearchSchedule,
  ResearchScheduleRun,
  ResearchJob,
  ResearchNotification,
  ResearchNotificationAttempt,
  AnalysisRun,
  ProductAnalysis,
  ContentCandidate,
  ContentGenerationRun,
  GeneratedContent,
  ContentValidationIssue,
  ContentReview,
  XPublication,
  XPublicationPost,
  XPostMetricSnapshot,
  XStrategyPerformance,
  XPublicationExperiment,
  XOptimizationRun,
  XOptimizationFinding,
  XOptimizationRecommendation,
  XOptimizationApplication,
  XContentVariant,
  XProductPublicationState,
  XProductPublicationReservation,
  XRuntimeControl,
  XOperationalAuditLog,
  XApiCredential,
  XOAuthSession,
  XApiRequestLog,
  XApiUsageSnapshot,
  XApiBudgetControl,
  AffiliateProviderRegistry,
  AffiliateProduct,
  ProductSnapshot,
  SourceDocument,
  ResearchFinding,
  TopicCandidate,
  ContentStrategy,
  Content,
  ContentVersion,
  Claim,
  ClaimSource,
  ContentVersionClaim,
  PolicyRule,
  PolicyEvaluation,
  QualityReviewRecord,
  RevisionAction,
  PublicationTarget,
  PublicationRecord,
  ProductLink,
  ProductLinkUsage,
  LinkReplacementEvent,
  AnalyticsSnapshot,
  AnalyticsAggregate,
  Evaluation,
  EvaluationFinding,
  Experiment,
  ExperimentVariant,
  ExperimentResult,
  LearningRule,
  StrategyFeedback,
  AnalyticsImportBatch,
  AnalyticsImportRow,
  AnalyticsAttribution,
  AffiliateResult,
  LearningRuleApplication,
  LearningRuleConflict,
  OperationJob,
  OperationCheckpoint,
  AuditEvent,
  ModelRun,
  CostRecord,
  BudgetSetting,
  PromptDefinition,
  OperatorJob,
  ArticleStructureObservation,
  ArticleFormatDefinition,
} from "@prisma/client";
